/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.glb --transform --shadows 
Files: scene.glb [596.36KB] > E:\Coding Projects\Web development\React Threejs Fiber\r3f-practice-projects\scene-scroll-animation\public\models\scene-transformed.glb [232.97KB] (61%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Scene(props) {
	const { nodes, materials } = useGLTF("./models/scene-transformed.glb");
	return (
		<group {...props} dispose={null}>
			<pointLight
				castShadow
				intensity={0.796}
				decay={2}
				color="#ffa600"
				position={[-2.618, 0.429, 1.859]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<pointLight
				castShadow
				intensity={0.796}
				decay={2}
				color="#ffa600"
				position={[-2.627, 0.189, 1.614]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<pointLight
				intensity={0.398}
				decay={2}
				color="#ffa600"
				position={[1.639, -0.109, 1.637]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<pointLight
				intensity={0.199}
				decay={2}
				color="#ffa600"
				position={[0.67, 0.123, -0.5]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<pointLight
				intensity={0.239}
				decay={2}
				color="#ffa600"
				position={[2.838, -0.127, -1.697]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<pointLight
				intensity={0.199}
				decay={2}
				color="#ffa600"
				position={[-0.13, 0.6, -3.665]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<pointLight
				intensity={0.199}
				decay={2}
				color="#ffa600"
				position={[-1.376, -0.245, -0.68]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<pointLight
				intensity={0.199}
				decay={2}
				color="#ffa600"
				position={[-0.973, 0.071, -0.862]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<pointLight
				intensity={0.199}
				decay={2}
				color="#ffa600"
				position={[0.094, 0.699, -3.814]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<pointLight
				intensity={1.592}
				decay={2}
				color="#ff8f00"
				position={[-0.551, -0.148, -3.71]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<pointLight
				intensity={0.637}
				decay={2}
				color="#ffa600"
				position={[3.035, 0.061, -1.736]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<pointLight
				intensity={0.796}
				decay={2}
				color="#ffa600"
				position={[2.899, 0.009, 2.973]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<pointLight
				intensity={0.796}
				decay={2}
				color="#ffa600"
				position={[1.432, -0.126, 3.738]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<pointLight
				intensity={1.592}
				decay={2}
				color="#ff8f00"
				position={[0.032, -0.148, -3.71]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<group rotation={[Math.PI / 2, 0, 0]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.group1101690769.geometry}
					material={materials.PaletteMaterial001}
				/>
				<mesh geometry={nodes.group1101690769_1.geometry} material={materials.PaletteMaterial002} />
			</group>
			<mesh
				geometry={nodes.Glass_Lamp_No_Shadow.geometry}
				material={materials.PaletteMaterial003}
				rotation={[Math.PI / 2, 0, 0]}
			/>
		</group>
	);
}

useGLTF.preload("./models/scene-transformed.glb");
